<a href="https://colab.research.google.com/github/Tserenkhand0616/Dive-into-code/blob/main/Implementation_of_matrix_product.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

[Problem 1] Matrix product is calculated manually
Solve the matrix product of A and B by hand.

Please also explain the calculation process using markdown text.

In [ ]:
G = np.zeros((3,3))
G[0,0]=a_ndarray[0,0]*b_ndarray[0,0]+a_ndarray[0,1]*b_ndarray[1,0]+a_ndarray[0,2]*b_ndarray[2,0]
G[0,1]=a_ndarray[0,0]*b_ndarray[0,1]+a_ndarray[0,1]*b_ndarray[1,1]+a_ndarray[0,2]*b_ndarray[2,1]
G[0,2]=a_ndarray[0,0]*b_ndarray[0,2]+a_ndarray[0,1]*b_ndarray[1,2]+a_ndarray[0,2]*b_ndarray[2,2]
G[1,0]=a_ndarray[1,0]*b_ndarray[0,0]+a_ndarray[1,1]*b_ndarray[1,0]+a_ndarray[1,2]*b_ndarray[2,0]
G[1,1]=a_ndarray[1,0]*b_ndarray[0,1]+a_ndarray[1,1]*b_ndarray[1,1]+a_ndarray[1,2]*b_ndarray[2,1]
G[1,2]=a_ndarray[1,0]*b_ndarray[0,2]+a_ndarray[1,1]*b_ndarray[1,2]+a_ndarray[1,2]*b_ndarray[2,2]
G[2,0]=a_ndarray[2,0]*b_ndarray[0,0]+a_ndarray[2,1]*b_ndarray[1,0]+a_ndarray[2,2]*b_ndarray[2,0]
G[2,1]=a_ndarray[2,0]*b_ndarray[0,1]+a_ndarray[2,1]*b_ndarray[1,1]+a_ndarray[2,2]*b_ndarray[2,1]
G[2,2]=a_ndarray[2,0]*b_ndarray[0,2]+a_ndarray[2,1]*b_ndarray[1,2]+a_ndarray[2,2]*b_ndarray[2,2]
print(G)

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


[Problem 2] Calculation by NumPy function
This matrix product of NumPy can be easily calculated using np.matmul() or np.dot() , or the @ operator.

Use these to calculate the matrix product.

In [ ]:
C1=np.matmul(a_ndarray,b_ndarray)
C2=np.dot(a_ndarray, b_ndarray)
C3=a_ndarray@b_ndarray
print("Using np.matmul {}".format(C1))
print("Using np.dot {}".format(C2))
print("Using @ {}".format(C3))

Using np.matmul [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
Using np.dot [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
Using @ [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


[Problem 3] Implementation of calculation of a certain element
When doing the calculations by hand, you may have first paid attention to row 0 of matrix A and column 0 of matrix B, and then performed the following calculations.

In [ ]:
D=np.zeros((3),dtype=np.int16)
for i in range(3):
    D[i]=(a_ndarray[0,i]*b_ndarray[i,0])
Z=np.sum(D)
print(Z)

6


[Problem 4] Creating a function that performs matrix multiplication
Extend the code in Problem 3 to complete the matrix product scratch implementation. It should be a function that takes matrices A and B as arguments and returns the matrix product.

In [ ]:
def Find_matrix_product(a_ndarray,b_ndarray):
  '''
  A function that calculates product of matrix

  Parameters:
  -------------
  a_ndarray = First matrix
  b_ndarray = Second matrix
  i = number of row
  k = number of column

  Return:
  -------------
  C = product of matrix
  '''
  C = np.zeros((a_ndarray.shape[0], b_ndarray.shape[1]), dtype=np.int16)
  for i in range(a_ndarray.shape[0]):
    for k in range(b_ndarray.shape[1]):
      C[i,k]=np.sum(a_ndarray[i,:]*b_ndarray[:,k])
  return C
H=Find_matrix_product(a_ndarray,b_ndarray)
print(H)


[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


[Problem 5] Judge the input whose calculation is not defined
Depending on the implementation method, the function created in Problem 4 may work even if this D and E array is input. In this case, incorrect calculations will be made. Also, even if an error occurs in the middle, a message that is hard to understand why the error occurred is displayed directly.

In [ ]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])
def Right_Find_matrix_product(a_ndarray, b_ndarray):
  '''
  A function that checks whether two matrices are suitable matrices for multiplication
  Parameters:
  -----------
  a_ndarray = First matrix
  b_ndarray = Second matrix

  Returns:
  C = product of matrices
  '''
  if(a_ndarray.shape[0]==b_ndarray.shape[1]):
    print("Suitable")
    C = Find_matrix_product(a_ndarray,b_ndarray)# If two matrices suitable it find product and print "Suitable"
    return C
  elif(a_ndarray.shape[1]==b_ndarray.shape[0]):# if two matrices order is not right, this will swap and find product and prind "Need two swap"
    print("Need to swap")
    z=np.copy(b_ndarray)
    b_ndarray=a_ndarraya
    a_ndarray=z
    C = Find_matrix_product(a_ndarray,b_ndarray)
    return C
  else: #If neither of the above conditions are met, this will print "does not fit"
    print("does not fit")
T=Right_Find_matrix_product(d_ndarray,e_ndarray)

does not fit


[Problem 6] Transposition
Transposing one matrix allows you to calculate the matrix product.

Transpose it using the np.transpose() or .T attributes and calculate the matrix product.

In [ ]:
def Real_Find_matrix_product(a_ndarray, b_ndarray):
  '''
  A function that checks whether two matrices are suitable matrices for multiplication
  Parameters:
  -----------
  a_ndarray = First matrix
  b_ndarray = Second matrix

  Returns:
  C = product of matrices
  '''
  if(a_ndarray.shape[0]==b_ndarray.shape[1]):# If two matrices suitable it find product and print "Suitable"
    C = Find_matrix_product(a_ndarray,b_ndarray)
   # for i in range(a_ndarray.shape[0]):
    # for k in range(b_ndarray.shape[1]):
      # C[i,k]=np.sum(a_ndarray[i,:]*b_ndarray[:,k])"#
    return C
  elif(a_ndarray.shape[1]==b_ndarray.shape[0]):# if two matrices order is not right, this will swap and find product and prind "Need two swap"
    print("swapped")
    z=np.copy(b_ndarray)
    b_ndarray=a_ndarraya
    a_ndarray=z
    C = Find_matrix_product(a_ndarray,b_ndarray)
    return C
  else:#If neither of the above conditions are met, this will tranpose second matrice and find product
    z=np.transpose(b_ndarray)
    C = Find_matrix_product(a_ndarray,z)
    return C
    print("no")
T=Real_Find_matrix_product(d_ndarray,e_ndarray)
print(T)

[[ 46  -4]
 [-34  73]]
